In [1]:
%pip install numpy
import numpy as np
print("NumPy version:", np.__version__)

Note: you may need to restart the kernel to use updated packages.
NumPy version: 2.3.5



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\user\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


Создание массивов разными методами

In [2]:
py_list = [1, 2, 3, 4, 5]
arr_from_list = np.array(py_list)
print("Массив из списка:", arr_from_list)


zeros_arr = np.zeros((3, 3))
print("Массив нулей:\n", zeros_arr)


range_arr = np.arange(0, 10, 2)
print("Arange:", range_arr)

Массив из списка: [1 2 3 4 5]
Массив нулей:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Arange: [0 2 4 6 8]


Демонстрация атрибутов массива

In [3]:
test_arr = np.array([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]])
print("Форма массива (shape):", test_arr.shape)
print("Тип данных (dtype):", test_arr.dtype)
print("Размерность (ndim):", test_arr.ndim)

Форма массива (shape): (2, 3)
Тип данных (dtype): float64
Размерность (ndim): 2


Срезы и доступ к элементам массива

In [5]:
print("Первый элемент:", test_arr[0])
print("Последний элемент:", test_arr[-1])
print("Срез первого элемента:", test_arr[0][1:3])
print("Весь массив в обратном порядке:", test_arr[::-1])

Первый элемент: [1.5 2.5 3.5]
Последний элемент: [4.5 5.5 6.5]
Срез первого элемента: [2.5 3.5]
Весь массив в обратном порядке: [[4.5 5.5 6.5]
 [1.5 2.5 3.5]]


Примеры векторных операций и базовых статистик

In [11]:
print("Среднее для самого первого массива:", arr_from_list.mean())
print("Сумма первого и третьего массивов:", arr_from_list + range_arr)
print("Поементное произведение первого и третьего массивов:", arr_from_list * range_arr)

Среднее для самого первого массива: 3.0
Сумма первого и третьего массивов: [ 1  4  7 10 13]
Поементное произведение первого и третьего массивов: [ 0  4 12 24 40]
